language: go

os:
  - linux

go:
  - "1.10"

install:
  - make dependencies
  - test -z "$(go fmt ./...)"
  - glyphcheck ./...
  - make dev

script: make test && make test-long && make cover && make bench

sudo: false

branches:
  only:
    - master
    - staging

notifications:
  email: false
